name = "cursor-reset"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "scripts"
run_worker_first = true
binding = "ASSETS"

[version_metadata]
binding = "CF_VERSION_METADATA"
